'use client';

import React, { useState } from 'react';
import { NovaState, RoleType, ConfidenceTier } from '@/lib/types';
import { 
  AlertCircle, 
  CheckCircle, 
  Check, 
  Copy, 
  ChevronDown, 
  ChevronUp, 
  UserCheck, 
  ShieldAlert, 
  FileCheck2, 
  X,
  Sparkles,
  ClipboardList,
  BarChart2,
  TrendingUp,
  Layers
} from 'lucide-react';

interface RecruiterConsoleProps {
  state: NovaState;
  roleType: RoleType;
  isOpen: boolean;
  onClose: () => void;
}

export const RecruiterConsole: React.FC<RecruiterConsoleProps> = ({
  state,
  roleType,
  isOpen,
  onClose
}) => {
  const [activeTab, setActiveTab] = useState<'assessment' | 'skills' | 'notes'>('assessment');
  const [showRawJson, setShowRawJson] = useState(false);
  const [copiedJson, setCopiedJson] = useState(false);

  const confidence = state.confidence || {
    tier: 'insufficient_evidence',
    rationale: 'Call in progress. Awaiting candidate responses.',
    coverage: 'Pending evaluation.'
  };

  const evidence = state.evidence || [];
  const openQuestions = state.open_questions || [];
  const flags = state.flags || [];

  const handleCopyJson = () => {
    navigator.clipboard.writeText(JSON.stringify(state, null, 2));
    setCopiedJson(true);
    setTimeout(() => setCopiedJson(false), 2000);
  };

  const expectedSkills = roleType === 'ENGINEERING'
    ? [
        'Distributed Systems Architecture',
        'Latency & Throughput Optimization',
        'Data Storage & Partitioning',
        'Fault Tolerance & Resilience',
        'Individual Technical Ownership'
      ]
    : [
        'Math Pedagogy & Simplification',
        'Student Empathy & Patience',
        'Online Classroom Engagement',
        'Parent Feedback & Communication'
      ];

  const matchedCount = expectedSkills.filter(skill => 
    evidence.some(e => 
      e.competency.toLowerCase().includes(skill.split(' ')[0].toLowerCase()) ||
      skill.toLowerCase().includes(e.competency.split(' ')[0].toLowerCase())
    )
  ).length;

  const matchPercent = Math.round((matchedCount / expectedSkills.length) * 100);

  const getStatusBadge = (tier: ConfidenceTier) => {
    switch (tier) {
      case 'high':
        return {
          title: 'Strong Fit (High Confidence)',
          pillClass: 'bg-emerald-100 text-emerald-900 border-emerald-300 font-bold',
          icon: <CheckCircle className="w-5 h-5 text-emerald-600" />,
          cardClass: 'bg-emerald-50/80 border-emerald-300 shadow-xs'
        };
      case 'medium':
        return {
          title: 'Moderate Fit (Medium Confidence)',
          pillClass: 'bg-blue-100 text-blue-900 border-blue-300 font-bold',
          icon: <UserCheck className="w-5 h-5 text-blue-600" />,
          cardClass: 'bg-blue-50/80 border-blue-300 shadow-xs'
        };
      case 'low':
        return {
          title: 'Gaps Identified (Low Confidence)',
          pillClass: 'bg-rose-100 text-rose-900 border-rose-300 font-bold',
          icon: <ShieldAlert className="w-5 h-5 text-rose-600" />,
          cardClass: 'bg-rose-50/80 border-rose-300 shadow-xs'
        };
      case 'insufficient_evidence':
      default:
        return {
          title: 'Collecting Evidence',
          pillClass: 'bg-amber-100 text-amber-900 border-amber-300 font-bold',
          icon: <AlertCircle className="w-5 h-5 text-amber-600" />,
          cardClass: 'bg-amber-50/70 border-amber-300 border-dashed'
        };
    }
  };

  const status = getStatusBadge(confidence.tier);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 bg-slate-950/60 backdrop-blur-md animate-in fade-in duration-200">
      <div 
        className="w-full max-w-2xl bg-white border border-slate-200 rounded-t-3xl sm:rounded-3xl shadow-2xl overflow-hidden max-h-[88vh] flex flex-col animate-in slide-in-from-bottom-8 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Drawer Header */}
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-slate-950 text-white shadow-md">
              <Layers className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-sm font-extrabold text-slate-950">Candidate Evaluation & Insights</h2>
                <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded-full bg-slate-200 text-slate-800">
                  {roleType}
                </span>
              </div>
              <p className="text-xs text-slate-500 font-medium">Real-time interview assessment generated by Nova</p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-slate-900 hover:bg-slate-200 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="px-6 pt-3 pb-2 bg-white border-b border-slate-100">
          <div className="grid grid-cols-3 gap-1.5 p-1 bg-slate-100 rounded-2xl text-xs font-semibold text-slate-600">
            <button
              onClick={() => setActiveTab('assessment')}
              className={`py-2 rounded-xl transition-all flex items-center justify-center gap-1.5 ${
                activeTab === 'assessment'
                  ? 'bg-white text-slate-950 shadow-xs font-bold'
                  : 'hover:text-slate-950'
              }`}
            >
              <BarChart2 className="w-3.5 h-3.5" />
              <span>Assessment</span>
            </button>

            <button
              onClick={() => setActiveTab('skills')}
              className={`py-2 rounded-xl transition-all flex items-center justify-center gap-1.5 ${
                activeTab === 'skills'
                  ? 'bg-white text-slate-950 shadow-xs font-bold'
                  : 'hover:text-slate-950'
              }`}
            >
              <FileCheck2 className="w-3.5 h-3.5 text-indigo-600" />
              <span>Verified Skills ({evidence.length})</span>
            </button>

            <button
              onClick={() => setActiveTab('notes')}
              className={`py-2 rounded-xl transition-all flex items-center justify-center gap-1.5 ${
                activeTab === 'notes'
                  ? 'bg-white text-slate-950 shadow-xs font-bold'
                  : 'hover:text-slate-950'
              }`}
            >
              <ClipboardList className="w-3.5 h-3.5 text-amber-600" />
              <span>Notes ({openQuestions.length + flags.length})</span>
            </button>
          </div>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto space-y-4 flex-1 bg-slate-50/40">
          {/* TAB 1: ASSESSMENT */}
          {activeTab === 'assessment' && (
            <div className="space-y-4 animate-in fade-in duration-150">
              {/* Main Status Banner */}
              <div className={`p-5 rounded-2xl border ${status.cardClass} space-y-3.5`}>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2.5">
                    {status.icon}
                    <span className="text-sm font-bold text-slate-950">{status.title}</span>
                  </div>
                  <span className={`text-[11px] font-mono px-3 py-1 rounded-full border ${status.pillClass}`}>
                    {confidence.tier.toUpperCase().replace('_', ' ')}
                  </span>
                </div>

                <div className="bg-white/95 p-4 rounded-xl border border-slate-200 shadow-2xs">
                  <div className="text-[10px] uppercase font-bold text-slate-400 mb-1 tracking-wider">Evaluation Rationale</div>
                  <p className="text-xs sm:text-sm text-slate-800 leading-relaxed font-normal">
                    {confidence.rationale}
                  </p>
                </div>
              </div>

              {/* Match Percentage */}
              <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3">
                <div className="flex items-center justify-between text-xs sm:text-sm">
                  <span className="font-bold text-slate-950">Role Requirements Match</span>
                  <span className="font-mono font-extrabold text-indigo-600 text-sm">{matchPercent}%</span>
                </div>

                <div className="w-full bg-slate-100 rounded-full h-2.5 overflow-hidden border border-slate-200">
                  <div 
                    className="bg-indigo-600 h-2.5 rounded-full transition-all duration-300"
                    style={{ width: `${Math.max(matchPercent, 5)}%` }}
                  />
                </div>

                <div className="space-y-2 pt-2">
                  {expectedSkills.map((skill, idx) => {
                    const isVerified = evidence.some(e => 
                      e.competency.toLowerCase().includes(skill.split(' ')[0].toLowerCase()) ||
                      skill.toLowerCase().includes(e.competency.split(' ')[0].toLowerCase())
                    );

                    return (
                      <div
                        key={idx}
                        className={`flex items-center justify-between p-3 rounded-xl border text-xs transition-all ${
                          isVerified
                            ? 'bg-emerald-50/80 border-emerald-200 text-emerald-950 font-bold'
                            : 'bg-slate-50/70 border-slate-200 text-slate-500'
                        }`}
                      >
                        <div className="flex items-center gap-2.5 truncate">
                          <span className={`w-2 h-2 rounded-full ${isVerified ? 'bg-emerald-500 shadow-xs' : 'bg-slate-300'}`} />
                          <span className="truncate">{skill}</span>
                        </div>
                        <span className="text-[10px] font-mono font-bold">
                          {isVerified ? 'VERIFIED' : 'PENDING'}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: VERIFIED SKILLS */}
          {activeTab === 'skills' && (
            <div className="space-y-3 animate-in fade-in duration-150">
              {evidence.length === 0 ? (
                <div className="text-center py-14 border border-dashed border-slate-200 rounded-2xl bg-white p-6">
                  <FileCheck2 className="w-10 h-10 text-slate-300 mx-auto mb-2" />
                  <p className="text-sm font-bold text-slate-800">No verified skills yet</p>
                  <p className="text-xs text-slate-400 mt-1">Nova is actively listening and exploring candidate skills during the call.</p>
                </div>
              ) : (
                evidence.map((item, idx) => (
                  <div
                    key={idx}
                    className="p-4 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-2"
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold text-slate-900 bg-slate-100 px-3 py-1 rounded-full border border-slate-200">
                        {item.competency}
                      </span>
                      <span className="text-[10px] font-mono px-2.5 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200 font-bold">
                        {item.specificity}
                      </span>
                    </div>

                    <p className="text-xs sm:text-sm text-slate-800 font-medium leading-relaxed">
                      {item.claim}
                    </p>

                    {item.verbatim && (
                      <div className="text-xs font-mono text-slate-600 bg-slate-50 p-3 rounded-xl border border-slate-200">
                        <span className="text-indigo-500 mr-1">&quot;</span>
                        {item.verbatim}
                        <span className="text-indigo-500 ml-1">&quot;</span>
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>
          )}

          {/* TAB 3: NOTES */}
          {activeTab === 'notes' && (
            <div className="space-y-3 animate-in fade-in duration-150">
              {openQuestions.length === 0 && flags.length === 0 ? (
                <div className="text-center py-14 border border-dashed border-slate-200 rounded-2xl bg-white p-6">
                  <ClipboardList className="w-10 h-10 text-slate-300 mx-auto mb-2" />
                  <p className="text-sm font-bold text-slate-800">No pending follow-ups</p>
                  <p className="text-xs text-slate-400 mt-1">All candidate questions were answered directly from fact sheets.</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {openQuestions.map((q, idx) => (
                    <div
                      key={`q-${idx}`}
                      className="p-4 rounded-2xl bg-indigo-50/90 border border-indigo-200 text-xs sm:text-sm text-indigo-950 shadow-xs space-y-1"
                    >
                      <div className="font-bold text-indigo-900">
                        Follow-up for {roleType === 'ENGINEERING' ? 'Priya' : 'Arjun'}:
                      </div>
                      <p className="text-indigo-950 leading-relaxed font-medium">{q}</p>
                    </div>
                  ))}

                  {flags.map((f, idx) => (
                    <div
                      key={`f-${idx}`}
                      className="p-4 rounded-2xl bg-rose-50/90 border border-rose-200 text-xs sm:text-sm text-rose-950 shadow-xs space-y-1"
                    >
                      <div className="font-bold text-rose-900">Candidate Flag:</div>
                      <p className="text-rose-950 leading-relaxed font-medium">{f}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Drawer Footer with Raw Data Toggle */}
        <div className="p-4 border-t border-slate-200 bg-slate-50 flex items-center justify-between">
          <button
            onClick={() => setShowRawJson(!showRawJson)}
            className="text-xs text-slate-600 font-mono hover:text-slate-900 flex items-center gap-1"
          >
            <span>Raw State JSON</span>
            {showRawJson ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
          </button>

          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-slate-950 text-white text-xs font-bold shadow-md hover:bg-slate-800 transition-all"
          >
            Close Insights
          </button>
        </div>

        {showRawJson && (
          <div className="p-4 bg-slate-950 text-slate-200 space-y-2 border-t border-slate-800">
            <div className="flex justify-end">
              <button
                onClick={handleCopyJson}
                className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 rounded text-[10px] font-mono text-slate-300 flex items-center gap-1"
              >
                {copiedJson ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                <span>{copiedJson ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
            <pre className="font-mono text-[10px] text-slate-300 max-h-40 overflow-y-auto p-2 bg-black/40 rounded">
              {JSON.stringify(state, null, 2)}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
};
